// ---------- Mock data ----------

import { DeckItem } from "@/types/presentation/deck";

export const DATA: DeckItem[] = [
  {
    id: "1",
    title: "Product Launch",
    description:
      "Opening hook, problem framing, three feature highlights, and a closing CTA slide.",
    color: "#A0A3FF",
    updatedAt: new Date(2026, 5, 23, 12, 34),
    slideCount: 65,
    durationMins: 8,
    isFavourite: false,
  },
  {
    id: "2",
    title: "Q3 Investor Update",
    description: "Revenue, churn, roadmap.",
    color: "#FFC88A",
    updatedAt: new Date(2026, 5, 21, 9, 10),
    slideCount: 45,
    durationMins: 5,
    isFavourite: true,
  },
  {
    id: "3",
    title: "Team Onboarding Deck",
    description:
      "Company values, org chart walkthrough, tools setup, first-week expectations, and where to find help when you're stuck.",
    color: "#EFC1FF",
    updatedAt: new Date(2026, 5, 20, 16, 2),
    slideCount: 37,
    durationMins: 14,
    isFavourite: false,
  },
  {
    id: "4",
    title: "Design Review",
    description: "Wireframes for the onboarding flow.",
    color: "#A1AFDE",
    updatedAt: new Date(2026, 5, 18, 11, 45),
    slideCount: 56,
    durationMins: 6,
    isFavourite: false,
  },
  {
    id: "5",
    title: "Conference Talk",
    description: "Intro, three case studies, takeaways.",
    color: "#F78199",
    updatedAt: new Date(2026, 5, 15, 14, 0),
    slideCount: 35,
    durationMins: 20,
    isFavourite: true,
  },
  {
    id: "6",
    title: "Sales Pitch v2",
    description:
      "Updated pricing tiers, competitor comparison table, and customer testimonial slide added after last week's feedback.",
    color: "#ACCCC0",
    updatedAt: new Date(2026, 5, 12, 17, 30),
    slideCount: 28,
    durationMins: 7,
    isFavourite: false,
  },
  {
    id: "7",
    title: "Product Launch",
    description:
      "Opening hook, problem framing, three feature highlights, and a closing CTA slide.",
    color: "#A0A3FF",
    updatedAt: new Date(2026, 5, 23, 12, 34),
    slideCount: 65,
    durationMins: 8,
    isFavourite: false,
  },
  {
    id: "8",
    title: "Q3 Investor Update",
    description: "Revenue, churn, roadmap.",
    color: "#FFC88A",
    updatedAt: new Date(2026, 5, 21, 9, 10),
    slideCount: 45,
    durationMins: 5,
    isFavourite: true,
  },
  {
    id: "9",
    title: "Team Onboarding Deck",
    description:
      "Company values, org chart walkthrough, tools setup, first-week expectations, and where to find help when you're stuck.",
    color: "#EFC1FF",
    updatedAt: new Date(2026, 5, 20, 16, 2),
    slideCount: 37,
    durationMins: 14,
    isFavourite: false,
  },
  {
    id: "10",
    title: "Design Review",
    description: "Wireframes for the onboarding flow.",
    color: "#A1AFDE",
    updatedAt: new Date(2026, 5, 18, 11, 45),
    slideCount: 56,
    durationMins: 6,
    isFavourite: false,
  },
  {
    id: "11",
    title: "Product Launch",
    description:
      "Opening hook, problem framing, three feature highlights, and a closing CTA slide.",
    color: "#A0A3FF",
    updatedAt: new Date(2026, 5, 23, 12, 34),
    slideCount: 65,
    durationMins: 8,
    isFavourite: false,
  },
  {
    id: "12",
    title: "Q3 Investor Update",
    description: "Revenue, churn, roadmap.",
    color: "#FFC88A",
    updatedAt: new Date(2026, 5, 21, 9, 10),
    slideCount: 45,
    durationMins: 5,
    isFavourite: true,
  },
  {
    id: "13",
    title: "Team Onboarding Deck",
    description:
      "Company values, org chart walkthrough, tools setup, first-week expectations, and where to find help when you're stuck.",
    color: "#EFC1FF",
    updatedAt: new Date(2026, 5, 20, 16, 2),
    slideCount: 37,
    durationMins: 14,
    isFavourite: false,
  },
  {
    id: "14",
    title: "Design Review",
    description: "Wireframes for the onboarding flow.",
    color: "#A1AFDE",
    updatedAt: new Date(2026, 5, 18, 11, 45),
    slideCount: 56,
    durationMins: 6,
    isFavourite: false,
  },
];
