import React, { useEffect } from "react";
import { Image, StyleSheet } from "react-native";
import Animated, {
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withDelay,
  withTiming,
} from "react-native-reanimated";

/**
 * [LOTTIE-REPLACE]
 *
 * A baked PNG of scattered confetti with a one-shot settle animation, standing
 * in for a particle burst. Source: assets/mascots/confetti.svg, regenerated by
 * `node scripts/mascots/bake.mjs` (the pieces are scattered by a seeded PRNG so
 * the art is reproducible).
 *
 * To swap in a Lottie: replace the <Image> with <LottieView autoPlay loop={false} />
 * and drop the scale/opacity animation — a real burst animates its own pieces,
 * and scaling the whole sheet on top of that looks wrong.
 */
export function Confetti({ width = 320, height = 220 }: { width?: number; height?: number }) {
  const progress = useSharedValue(0);

  useEffect(() => {
    // Lands just after the mascot appears, so the two read as one beat rather
    // than as two separate things arriving.
    progress.value = withDelay(
      120,
      withTiming(1, { duration: 620, easing: Easing.out(Easing.cubic) }),
    );
  }, [progress]);

  const style = useAnimatedStyle(() => ({
    opacity: progress.value,
    // Expands slightly outward from the mascot, the way thrown confetti does.
    transform: [{ scale: 0.82 + progress.value * 0.18 }],
  }));

  return (
    <Animated.View style={[StyleSheet.absoluteFill, styles.centre, style]} pointerEvents="none">
      <Image
        source={require("../../../../assets/mascots/confetti.png")}
        style={{ width, height }}
        resizeMode="contain"
        accessibilityElementsHidden
        importantForAccessibility="no-hide-descendants"
      />
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  centre: { alignItems: "center", justifyContent: "center" },
});
