import React, { useEffect } from "react";
import { ImageStyle, StyleProp } from "react-native";
import { Asset } from "expo-asset";
import { Image } from "expo-image";
import SkiaMascot from "@/components/ui/skia-mascot";
import Animated, {
  Easing,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withSequence,
  withTiming,
} from "react-native-reanimated";

/**
 * [LOTTIE-REPLACE]
 *
 * The mascot is a baked PNG plus a Reanimated bob, not an animated character.
 * Source SVGs live in assets/mascots/*.svg and are regenerated by
 * `node scripts/mascots/bake.mjs` — edit those, never the PNGs.
 *
 * To swap in a Lottie: use `LottieMascot` below (Skia, like every animated
 * mascot) in place of the <Image>, then delete the bob — a real animation
 * carries its own idle motion and the two will fight.
 */

const MASCOT_SOURCES = {
  error: require("../../../../assets/mascots/mascot-error.png"),
  search: require("../../../../assets/mascots/mascot-search.png"),
  noResults: require("../../../../assets/mascots/mascot-no-results.png"),
};

export type MascotPose = keyof typeof MASCOT_SOURCES;

/**
 * Warm expo-image's memory cache with every pose, at launch.
 *
 * Through expo-image rather than `Asset.loadAsync`: in a dev build the image is
 * a Metro URL, and only a prefetch into the same cache the <Image> reads from
 * stops it being fetched again the first time an empty state appears.
 */
export function preloadMascots(): Promise<boolean> {
  return Image.prefetch(
    Object.values(MASCOT_SOURCES).map((source) => Asset.fromModule(source).uri),
    "memory-disk",
  );
}

/**
 * A state-machine Lottie mascot in a `size` layout box, standing in for a PNG
 * pose of the same size. The files draw the character at ~41% of their canvas,
 * so the canvas is twice the box and overflows it evenly: the character fills
 * about 82% of the box, and nothing around it has to move.
 */
export function LottieMascot({
  mascot,
  size,
}: {
  mascot: { source: number };
  size: number;
}) {
  const canvas = size * 2;
  return (
    <SkiaMascot
      source={mascot.source}
      width={canvas}
      style={{ margin: -(canvas - size) / 2 }}
    />
  );
}

interface MascotProps {
  pose: MascotPose;
  size?: number;
  style?: StyleProp<ImageStyle>;
  /** Idle bob. Off for a static context (a list row, a screenshot). */
  animated?: boolean;
}

export function Mascot({
  pose,
  size = 116,
  style,
  animated = true,
}: MascotProps) {
  const bob = useSharedValue(0);

  useEffect(() => {
    if (!animated) return;
    // A slow, shallow float — this is a calm screen, and a mascot that bounces
    // hard reads as a loading spinner. 2.4s is slower than a breath on purpose.
    bob.value = withRepeat(
      withSequence(
        withTiming(1, { duration: 1200, easing: Easing.inOut(Easing.sin) }),
        withTiming(0, { duration: 1200, easing: Easing.inOut(Easing.sin) }),
      ),
      -1,
      false,
    );
  }, [animated, bob]);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [
      { translateY: bob.value * -6 },
      { rotate: `${bob.value * 1.5 - 0.75}deg` },
    ],
  }));

  return (
    <Animated.View style={animated ? animatedStyle : undefined}>
      <Image
        source={MASCOT_SOURCES[pose]}
        style={[{ width: size, height: size }, style]}
        contentFit="contain"
        cachePolicy="memory-disk"
        // Decorative. Announcing "blue blob" adds nothing for a screen reader.
        accessibilityElementsHidden
        importantForAccessibility="no-hide-descendants"
      />
    </Animated.View>
  );
}
