export const fonts = {
  krona: "Krona One",

  amarna: {
    thin: "Amarna-Thin",
    thinItalic: "Amarna-ThinItalic",
    extraLight: "Amarna-ExtraLight",
    extraLightItalic: "Amarna-ExtraLightItalic",
    light: "Amarna-Light",
    lightItalic: "Amarna-LightItalic",
    regular: "Amarna",
    italic: "Amarna-Italic",
    medium: "Amarna-Medium",
    mediumItalic: "Amarna-MediumItalic",
    semiBold: "Amarna-SemiBold",
    semiBoldItalic: "Amarna-SemiBoldItalic",
    bold: "Amarna-Bold",
    boldItalic: "Amarna-BoldItalic",
  },

  newsreader: {
    extraLight: "Newsreader-ExtraLight",
    extraLightItalic: "Newsreader-ExtraLightItalic",
    light: "Newsreader-Light",
    lightItalic: "Newsreader-LightItalic",
    regular: "Newsreader",
    italic: "Newsreader-Italic",
    medium: "Newsreader-Medium",
    mediumItalic: "Newsreader-MediumItalic",
    semiBold: "Newsreader-SemiBold",
    semiBoldItalic: "Newsreader-SemiBoldItalic",
    bold: "Newsreader-Bold",
    boldItalic: "Newsreader-BoldItalic",
    extraBold: "Newsreader-ExtraBold",
    extraBoldItalic: "Newsreader-ExtraBoldItalic",
  },
};
