"""revalidate all models

Revision ID: 063c8b0da287
Revises: 68eab3d42eb9
Create Date: 2026-07-18 17:25:47.899902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063c8b0da287'
down_revision: Union[str, Sequence[str], None] = '68eab3d42eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    generation_status_enum = postgresql.ENUM(
        "pending",
        "processing",
        "completed",
        "failed",
        name="generation_status_enum",
    )

    experience_level_enum = postgresql.ENUM(
        "beginner",
        "intermediate",
        "advanced",
        "pro",
        name="experience_level_enum",
    )

    profession_enum = postgresql.ENUM(
        "business",
        "tech",
        "sales_marketing",
        "academic",
        "student",
        "healthcare",
        "finance_consulting",
        "legal",
        "creative",
        "government_nonprofit",
        "other",
        name="profession_enum",
    )

    subscription_tier_enum = postgresql.ENUM(
        "sketos",
        "metrios",
        "glykos",
        name="subscription_tier_enum",
    )

    user_role_enum = postgresql.ENUM(
        "user",
        "admin",
        name="user_role_enum",
    )

    generation_status_enum.create(op.get_bind(), checkfirst=True)
    experience_level_enum.create(op.get_bind(), checkfirst=True)
    profession_enum.create(op.get_bind(), checkfirst=True)
    subscription_tier_enum.create(op.get_bind(), checkfirst=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.add_column('cards', sa.Column('keywords', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('cards', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('cards', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint('uq_cards_deck_id_position', 'cards', ['deck_id', 'position'])
    op.drop_constraint(op.f('cards_deck_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    op.add_column('decks', sa.Column('recording_url', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('decks', sa.Column('generation_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generation_status_enum'), server_default='pending', nullable=False))
    op.add_column('decks', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('generation_error', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('generation_retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('decks', sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('decks', sa.Column('generation_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('decks', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('decks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('decks', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_index(op.f('ix_decks_celery_task_id'), 'decks', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_decks_generation_status'), 'decks', ['generation_status'], unique=False)
    op.create_index(op.f('ix_decks_is_deleted'), 'decks', ['is_deleted'], unique=False)
    op.create_index('ix_decks_user_id_created_at', 'decks', ['user_id', 'created_at'], unique=False)
    op.drop_column('decks', 'description')
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'PRO', name='experience_level_enum'), nullable=True))
    op.add_column('users', sa.Column('profession', sa.Enum('BUSINESS', 'TECH', 'SALES_MARKETING', 'ACADEMIC', 'STUDENT', 'HEALTHCARE', 'FINANCE_CONSULTING', 'LEGAL', 'CREATIVE', 'GOVERNMENT_NONPROFIT', 'OTHER', name='profession_enum'), nullable=True))
    op.add_column('users', sa.Column('monthly_generations_used', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('usage_period_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN subscription_tier
    TYPE subscription_tier_enum
    USING subscription_tier::subscription_tier_enum;
    """)
    op.execute("""
    UPDATE users
    SET subscription_tier = 'sketos'
    WHERE subscription_tier IS NULL;
    """)
    op.alter_column(
        "users",
        "subscription_tier",
        nullable=False,
    )
    op.execute("""
    UPDATE users
    SET role = 'user'
    WHERE role IS NULL;
    """)
    op.alter_column(
        "users",
        "role",
        nullable=False,
    )
    op.drop_column('users', 'name')
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.Enum('SKETOS', 'METRIOS', 'GLYKOS', name='subscription_tier_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'usage_period_started_at')
    op.drop_column('users', 'monthly_generations_used')
    op.drop_column('users', 'profession')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'full_name')
    op.add_column('decks', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_decks_user_id_created_at', table_name='decks')
    op.drop_index(op.f('ix_decks_is_deleted'), table_name='decks')
    op.drop_index(op.f('ix_decks_generation_status'), table_name='decks')
    op.drop_index(op.f('ix_decks_celery_task_id'), table_name='decks')
    op.drop_column('decks', 'version')
    op.drop_column('decks', 'deleted_at')
    op.drop_column('decks', 'is_deleted')
    op.drop_column('decks', 'generation_completed_at')
    op.drop_column('decks', 'generation_started_at')
    op.drop_column('decks', 'generation_retry_count')
    op.drop_column('decks', 'generation_error')
    op.drop_column('decks', 'celery_task_id')
    op.drop_column('decks', 'generation_status')
    op.drop_column('decks', 'is_public')
    op.drop_column('decks', 'recording_url')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_deck_id_fkey'), 'cards', 'decks', ['deck_id'], ['id'])
    op.drop_constraint('uq_cards_deck_id_position', 'cards', type_='unique')
    op.alter_column('cards', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('cards', 'version')
    op.drop_column('cards', 'keywords')
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('practice_reminders_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('practice_reminder_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_mood', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###
