"""add partial index for public decks feed

Revision ID: 54fc326a4193
Revises: f0c4ad06abd2
Create Date: 2026-08-09 14:51:30.496160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fc326a4193'
down_revision: Union[str, Sequence[str], None] = 'f0c4ad06abd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_decks_public_feed', 'decks', ['is_public', 'created_at', 'id'], unique=False, postgresql_where=sa.text('is_public = true AND is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decks_public_feed', table_name='decks', postgresql_where=sa.text('is_public = true AND is_deleted = false'))
    # ### end Alembic commands ###
