"""refactor description to optional and added new field as script

Revision ID: 68eab3d42eb9
Revises: 
Create Date: 2026-07-03 20:31:39.389046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eab3d42eb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('script', sa.String(), nullable=True))
    op.alter_column('decks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('decks', 'script')
    # ### end Alembic commands ###
