"""added audio_key and key_upload time to deck model

Revision ID: 69b0209c0c80
Revises: c3f81a67d420
Create Date: 2026-08-01 18:38:13.717058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b0209c0c80'
down_revision: Union[str, Sequence[str], None] = 'c3f81a67d420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.add_column('decks', sa.Column('audio_key', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('audio_uploaded_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_script_generations_cards_task'), table_name='script_generations')
    op.create_index(op.f('ix_script_generations_cards_celery_task_id'), 'script_generations', ['cards_celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_generations_cards_celery_task_id'), table_name='script_generations')
    op.create_index(op.f('ix_script_generations_cards_task'), 'script_generations', ['cards_celery_task_id'], unique=False)
    op.drop_column('decks', 'audio_uploaded_at')
    op.drop_column('decks', 'audio_key')
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('practice_reminders_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('practice_reminder_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_mood', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###
