"""restore the user_preferences table

It was dropped by 063c8b0da287 ("revalidate all models"), which was
autogenerated at a time when migrations/env.py imported only User, Deck and
Card. Autogenerate diffs the database against Base.metadata, so a table whose
model was never imported reads as an orphan — and the generated migration
dutifully dropped it. The model never went anywhere, so every
`GET /api/v1/preferences` has raised UndefinedTable since.

env.py now imports every model, which is what stops this recurring.

Revision ID: e5b3a1f60c92
Revises: d21a9c4e77b1
Create Date: 2026-08-16

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "e5b3a1f60c92"
down_revision: Union[str, Sequence[str], None] = "d21a9c4e77b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Guarded because the table's absence is environment-specific: a database
    # that was created after the drop has no table, while one restored from an
    # older backup may still have it. Both should end up here.
    if "user_preferences" in inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("practice_reminders_enabled", sa.Boolean(), nullable=False),
        sa.Column("practice_reminder_time", sa.String(), nullable=False),
        sa.Column("default_mood", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # Unique, matching the model: preferences are one row per user, and the
    # controller's `.first()` would otherwise silently pick one of several.
    op.create_index(
        "ix_user_preferences_user_id", "user_preferences", ["user_id"], unique=True
    )


def downgrade() -> None:
    op.drop_index("ix_user_preferences_user_id", table_name="user_preferences")
    op.drop_table("user_preferences")
