"""add is_public to script_generations

Revision ID: f0c4ad06abd2
Revises: b8d1e35a07c4
Create Date: 2026-08-05 22:57:12.119776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c4ad06abd2'
down_revision: Union[str, Sequence[str], None] = 'b8d1e35a07c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_generations', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_generations', 'is_public')
    # ### end Alembic commands ###
